lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index')
]

lab_5/urls.py
from django.conf.urls import url
from .views import index, add_todo

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls
import lab_3.urls
import lab_4.urls
import lab_5.urls
import lab_6.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon.urls,namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3.urls,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4.urls,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5.urls, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6.urls, namespace='lab-6')),
    url(r'^$', RedirectView.as_view(url='lab-5/'), name='lab-5'),
    #url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico',permanent=True)),
]

lab_5/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=99)
    description = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

lab_5/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Input title here'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Describe description here'
    }

    title = forms.CharField(label='', required=True, max_length=99, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

lab_5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from.forms import Todo_Form
from.models import Todo
from lab_1.views import mhs_name

# Create your views here.
response = {}
def index(request):    
    response['author'] = mhs_name #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    html = 'lab_5/lab_5.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['title'] = request.POST['title']
        response['description'] = request.POST['description']
        todo = Todo(title=response['title'],description=response['description'])
        todo.save()
        return HttpResponseRedirect('/lab-5/')
    else:
        return HttpResponseRedirect('/lab-5/')

def delete_todo(request):
    return HttpResponseRedirect('/lab-5/')

templates/lab_5/partials/footer.html
<p>Copyright &copy; 2017 by {{author}}. All Rights Reserved.</p>

templates/lab_5/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- LINK MENUJU table, dan link menuju home#form -->
        <li><a href="{% url 'lab-5:index' %}#input-list">Input Todo</a></li>
        <li><a href="{% url 'lab-5:index' %}#my-list">My List</a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>